---
title: "Gestalt Principles"
format: html
execute: 
  warning: false
  echo: true
  error: false
---

```{r}
#| label: setup
#| include: false

#load hte tidyverse
library(tidyverse)  #can also add comments here

#set the default theme for all graphs
theme_set(theme_light())
```

## Fake Data  

First, let's read in the data.  
```{r}
fake_data <- read_csv("fake_data.csv")
```

### Proximity  

```{r}
#create a dodged bar chart of fake data


#code with no comments
fake_data |> 
  ggplot(aes(x = Factor1, y = Response)) +
  geom_col(aes(fill = Factor2), 
           position = "dodge",
           color = "black")

#same basic code below! With comments added

#take the fake_data, and then... 
# |> is called the "native pipe" and it means "and then"
fake_data |> 
  #initiate a plot and set the x and y variable mappings
  #aes stands for "aesthetic"
  # + is the same as a pipe, but only use it inside ggplot code
  ggplot(aes(x = Factor1, y = Response)) +
  #set the geometry to a bar plot, fill the column color based on Factor2
  #geom_col because we specify the height of the bar with y
  geom_col(aes(fill = Factor2), 
           position = "dodge",
           color = "black") +
  labs(title = "Bar graph of factor relationships",
       x = "Levels of Factor 1",
       fill = "2nd Factor")
  #example of adding a color scale
  #scale_fill_viridis_d()
```

### Encolsure + Proximity 

```{r}
fake_data |>
  ggplot(aes(x = Factor1, y = Response)) +
  geom_col(aes(fill = Factor2),
           color = "black") +
  facet_wrap(~Factor2) 
```

### Similarity  

```{r}
fake_data |>
  ggplot(aes(x = Factor1, y = Response)) +
  geom_point(aes(shape = Factor2,
                 color = Factor2), 
             size = 6)
```

### Similarity + Connection

```{r}
#why are some aesthetic mapings in ggplot, and some are in the geometry?
#think of ggplot aesthetics as "global." For any geometry, these mappings will be true. 
#anny mappings that are specific to the geometry should only be included in the aes for that geometry

#Both sets of code below create the same graph

fake_data |>
  ggplot(aes(x = Factor1, y = Response)) +
  geom_point(aes(shape = Factor2,
                 color = Factor2), 
             size = 6) +
  geom_line(aes(group = Factor2,
                color = Factor2), 
            linewidth = 2) 

fake_data |>
  ggplot(aes(x = Factor1, y = Response, color = Factor2)) +
  geom_point(aes( shape = Factor2),
             size = 6) +
  geom_line(aes(group = Factor2), 
            linewidth = 2) 
```

### Similarity + Connection

```{r}
fake_data |> 
  mutate(is_A = (Factor2 == "A")) |>
  ggplot(aes(x = Factor1, 
             y = Response, 
             color = is_A)) +
  geom_point(aes(shape = Factor2), 
             size = 6) +
  geom_line(aes(group = Factor2), 
            linewidth = 2) +
  guides(color = "none")
```


### Enclosure + Similarity + Connection

```{r}
fake_data |>
  mutate(is_A = (Factor2 == "A")) |>
  ggplot(aes(x = Factor1, 
             y = Response, 
             color = is_A)) +
  geom_point(aes(shape = Factor2), 
             size = 6) +
  geom_line(aes(group = Factor2), 
            linewidth = 2) +
  guides(color = "none") +
  geom_rect(xmin = 0.75, xmax = 1.25, ymin = 2, ymax = 17, 
            fill = "beige", alpha = 0.1, color = "black") +
  geom_rect(xmin = 1.75, xmax = 3.25, ymin = 2, ymax = 17, 
            fill = "beige", alpha = 0.1, color = "black")

```


